### PR TITLE
Add instrumentSync method

### PR DESCRIPTION
**Pull request by jschilli**
trying to move ember-cli-blanket forward here.

see https://github.com/sglanzer/ember-cli-blanket/issues/103
https://github.com/sglanzer/ember-cli-blanket/issues/102 for background

would also resolve: 
https://github.com/sglanzer/ember-cli-blanket/issues/85

I'm open to feedback on naming and callback vs return setup - given the embedded callback for localStorage, I went with conditionals to deal with the callback vs return naming

### CODE REVIEW

**Comment by sfbwalder** [comment]
:+1:  for this to go forward to improve blanket / ember integration

**Comment by devinus** [comment]
:+1:

**Comment by jschilli** [comment]
@alex-seville any thoughts on this PR? alternate approach?

**Comment by jagthedrummer** [comment]
Would love to see this get merged to fix issues with ember-ci-blanket. :)

**Comment by rwjblue** [comment]
@alex-seville - Anything we can do to make this mereable?

**Comment by alex-seville** [comment]
This can be merged, but the main blanket build is currently broken and I don't have the time/resources to investigate why at the moment.

**Pull request merged**
