### PR TITLE
Adding support for EMAC Script 2015 (ES6)

### PR DESCRIPTION
**Pull request by gjurgens**
New **ES2015** `let` and `class` features requires the use of strict mode (`"use strict";`). If omitted issue #525 occurs.

This fix detects the inclusion of a global `"use strict";` and add the same annotation to the execution of the instrumented source code to avoid the SyntaxError thrown on the parsing process: 
`Error: BLANKET-Error parsing instrumented code: Error: BLANKET-Error parsing instrumented code: SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

This fix does **not** solve the use of function scoped strict mode, only when is used in global scope:
```javascript
function foo() {
    'use strict';
    var bar = 'This case is not fixed yet!';
    return bar;
}
```

**UPDATE:**
I've also had to upgrade [falafel](https://github.com/substack/node-falafel) version in another commit (please tell me if you prefer to shquash them into a single one), because the previous version of this library, had a bundled dependency with an old version of [esprima](https://github.com/jquery/esprima), which had no support for ES2015, and was interfering with the version included by Blanket.

One important thing, is that the new version of [falafel](https://github.com/substack/node-falafel), uses [acorn](https://github.com/marijnh/acorn) as it's default parser instead of [esprima](https://github.com/jquery/esprima). I don't know if you are ok with this new parser. If not, I think it's possible change [falafel's](https://github.com/substack/node-falafel) default parser. 

**One thing to take in mind with this**, is that [acorn](https://github.com/marijnh/acorn) has some UTF8 characters embedded into it's code, that may throw errors when loading on HTML pages with no UTF8 support. In my opinion this shouldn't be a problem, but please tell me if it is, and I'll try to find another solution.

Finally I've also added a new option to Blanket (`data-cover-ecmaVersion`) documented [here](https://github.com/gjurgens/blanket/blob/master/docs/options.md#data-cover-ecmaversion), to configure the EMACScript version to use by the parser. The default EMACScript version if this options is omitted is `5`;

Thanks, and please let me know if you need more info!

### CODE REVIEW

**Comment by listepo** [comment]
:+1:

**Comment by alex-seville** [comment]
This seems like a good change.  If the conflicts can be resolved I can merge and republish.

**Comment by gjurgens** [comment]
Thanks!
The fork should now be synced with the master branch, and ready to be merged.

**Comment by LinusU** [comment]
I would love ES2015 support! Currently hitting some problems with this branch though:

```text
Error: BLANKET-Error parsing instrumented code: ReferenceError: _$jscoverage is not defined
    at /my-project/node_modules/blanket/src/index.js:177:37
    at Object.__dirname.blanket._blanket.instrument (/my-project/node_modules/blanket/src/blanket.js:126:17)
    at Object.require.extensions..js (/my-project/node_modules/blanket/src/index.js:158:25)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Suite.<anonymous> (/my-project/node_modules/mocha/lib/interfaces/bdd.js:30:18)
    at emitThree (events.js:102:20)
    at Suite.emit (events.js:175:7)
    at /my-project/node_modules/mocha/lib/mocha.js:215:11
    at Array.forEach (native)
    at Mocha.loadFiles (/my-project/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/my-project/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/my-project/node_modules/mocha/bin/_mocha:393:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

This is the error I get on the current npm version:

```text
Error: Line 15: Unexpected reserved word
    at throwError (/my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:1467:21)
    at throwUnexpected (/my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:1516:17)
    at parsePrimaryExpression (/my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:1833:16)
    at /my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:3588:38
    at trackLeftHandSideExpressionAllowCall (/my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:3492:61)
    at parsePostfixExpression (/my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:1939:20)
    at /my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:3588:38
    at parseUnaryExpression (/my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:2009:16)
    at /my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:3588:38
    at parseBinaryExpression (/my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:2097:16)
    at /my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:3588:38
    at parseConditionalExpression (/my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:2144:16)
    at /my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:3588:38
    at parseAssignmentExpression (/my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:2167:16)
    at /my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:3588:38
    at parseExpression (/my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:2191:20)
    at /my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:3588:38
    at parseStatement (/my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:2836:16)
    at /my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:3588:38
    at parseSourceElement (/my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:3068:24)
    at parseSourceElements (/my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:3106:29)
    at parseProgram (/my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:3119:16)
    at /my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:3588:38
    at parse (/my-project/node_modules/blanket/node_modules/falafel/node_modules/esprima/esprima.js:3815:23)
    at module.exports (/my-project/node_modules/blanket/node_modules/falafel/index.js:32:15)
    at Object.__dirname.blanket._blanket.instrument (/my-project/node_modules/blanket/src/blanket.js:115:37)
    at Object.require.extensions..js (/my-project/node_modules/blanket/src/index.js:155:25)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/my-project/node_modules/the-image-format/index.js:5:18)
    at Module._compile (module.js:425:26)
    at Module._extensions..js (module.js:432:10)
    at Object.require.extensions..js (/my-project/node_modules/blanket/src/index.js:181:17)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/my-project/test/basic.js:11:24)
    at Module._compile (module.js:425:26)
    at Module._extensions..js (module.js:432:10)
    at Object.require.extensions..js (/my-project/node_modules/blanket/src/index.js:181:17)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /my-project/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/my-project/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/my-project/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/my-project/node_modules/mocha/bin/_mocha:393:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

**Comment by matto1990** [comment]
This PR works well for me! It adds support for ES6 arrow functions which we have begun using in Node 5.0.0.

**Comment by matto1990** [comment]
Thanks for merging this! Is there a schedule for when a new version with this change in with be released? It looks like 1.1.7 back in May was the latest release according to Github.

**Comment by alex-seville** [comment]
Just published v1.2.0

**Comment by matto1990** [comment]
Thank you!

**Comment by vincentbernat** [comment]
The generated code looks like this:

```js
'use strict';
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
```

With strict, it's not possible to define a variable without `var`. In my case, if I only remove `use strict` from the first module, this fixes the situation. I can also fix that by replacing

```js
            intro += "if (typeof "+covVar+" === 'undefined') "+covVar+" = {};\n";
```

with

```js
            intro += "if (typeof "+covVar+" === 'undefined') var "+covVar+" = {};\n";
```

in `blanket.js`. Works for me but if I try to run the unittests, it fails immediately.

**Comment by rumkin** [comment]
To avoid usage of `var` it should use root scope `window` or `global` instead.

**Pull request merged**
